apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /opt/kubernetes/ssl/ca.pem
    server: https://192.168.144.110:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubelet-bootstrap:4a42fb
  name: default
current-context: default
preferences: {}
users:
- name: kubelet-bootstrap:4a42fb
  user:
    token: 4a42fb.ea5bb3ddb62ee992
