apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /opt/kubernetes/ssl/ca.pem
    server: https://192.168.144.100:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubelet-bootstrap:92d490
  name: default
current-context: default
preferences: {}
users:
- name: kubelet-bootstrap:92d490
  user:
    token: 92d490.241c4b14c23cade1
